### PR TITLE
List foreign key constraints in schema view

### PR DESCRIPTION
**Pull request by S-Harshit**
Added a table containing foreign key information in both edit-column view and edit-source-column view.
Has to be merged after PR polypheny/Polypheny-DB#299 (File system data source) is merged in PolyphenyDB.

Fixes #125  -List foreign key constraints in schema view of PolyphenyDB

Table Image:-
image

image

### CODE REVIEW

**Comment by nilshansen94** [comment]
Hi @S-Harshit, thank you for the great work!
I have a few suggestions to change a few details (see the printscreen with some comments). It would be great to have the foreign key table below the constraints table and to have a header "Foreign keys" (I used h6). Also the table in the edit-columns view is missing an empty `<th>` element at the end (see the circle). It would also be good to change the column header "Column Name" to "Columns", so it matches the other table.
fk

In the code I was wondering if it would not be better to work with the ForeignKey model for the `connections[]` field.
The code in the `ngOnInit` method looks problematic, since the `getUml` method contains asynchronous code and sets the `connections` field, while the `clearConnections` method is called after the `getUml` method and clears the `connections` field. It works because the asynchronous code is slower, but could lead to problems. It would be safer to clear the `connections` field in the `getUml` method before filling it with the new data.
The check with `stringify` and `includes` is also rather unsafe.

The current approach doesn't work for composite foreign keys. Here is an example of creating one:
```sql
CREATE TABLE "public"."aa"("a" BIGINT NOT NULL,"b" BIGINT NOT NULL,"c" BIGINT,"d" BIGINT,PRIMARY KEY ("a","b")) ON STORE "hsqldb";
CREATE TABLE "public"."bb"("a" BIGINT NOT NULL,"b" BIGINT,"c" BIGINT,"d" BIGINT,PRIMARY KEY ("a")) ON STORE "hsqldb";
ALTER TABLE "public"."bb" ADD CONSTRAINT "auto_fk_23" FOREIGN KEY ("c",d) REFERENCES "public"."aa"(a,"b") ON UPDATE RESTRICT ON DELETE RESTRICT;
```
This should lead to the following entry:
fk2

**Comment by S-Harshit** [comment]
@nilshansen94 I have made changes as suggested in my latest commit except for composite Foreign keys,  currently the composite foreign keys are being displayed as shown below. Could you please suggest some approach to deal with composite foreign keys.

image

**Comment by nilshansen94** [comment]
Hi @S-Harshit, I would work with a HashMap. The key of the entries are the FK names. When an entry already exists, you have to add the source and target columns. So for example the entry `auto_fk_23` already exists and during the iteration a second one comes up. Then you can append `, d` to the column name of the already existing entry (`c`) and do the same with the target column name. At the end you can convert the HashMap back to an array and make sure that it is assigned to the variable that is being rendered in the HTML.

**Comment by S-Harshit** [comment]
Hi @nilshansen94, I have tried a different approach let me know if it is okay.

**Review by nilshansen94 — APPROVED** [review]
Thank you for your work, @S-Harshit. I made some code improvements and decided to rename the fields in the foreign key model (on the backend as well). I will merge the PR soon.

**Pull request merged**
