### PR TITLE
Fix rendering bug in Plan Builder in Firefox

### PR DESCRIPTION
**Pull request by Pawanupadhyay10**
UI rendering fix in firefox.
Closes polypheny/Polypheny-DB#255

### CODE REVIEW

**Comment by vogti** [comment]
Thx @Pawanupadhyay10. I can confirm that this fixes the bug in Firefox. It is still rendered wrongly while moving an operator, but this is ok.

**Comment by Pawanupadhyay10** [comment]
hi@vogti, thanks for your feedback, it fixes the bug on firefox but on moving an operator it is rendering .Can I take another issue as well?

**Comment by vogti** [comment]
Thank you for your contribution to Polypheny! Of course you can take care of another issue if you like :)

**Review by nilshansen94 — APPROVED** [review]

**Comment by Pawanupadhyay10** [comment]
hi @vogti ,as it get merged ,so definitely I need to start with a new issue ,but i found that issues related to polypheny-UI are already taken .

**Comment by vogti** [comment]
There are [two](https://github.com/polypheny/Polypheny-DB/issues?q=is%3Aopen+is%3Aissue+label%3AA-ui+label%3AE-good-first-issue+sort%3Aupdated-desc) open issues related to the UI and not yet assigned to someone. Furthermore, there are some issues without any activity (e.g., 281, 254, 184). You can ask in one of these issues if the assigned person is still working on the issue and if not, I will assign the issue to you.

**Pull request merged**
