### PR TITLE
Search function for query history

### PR DESCRIPTION
**Pull request by earthshakira**
Made the initial changes for the search bar.

- created a SearchFilter which filters the history map and create a new filtered map
- The Search UI using inputs and cross icon

Screen Recording of the Working

Fixes #282

### CODE REVIEW

**Review by nilshansen94 — CHANGES_REQUESTED** [review]
Hi @earthshakira, thank you for this pull request! You implemented a very nice solution with the pipe.

A few requests:
- There is a small CSS bug when the search has no matches. The „empty“-item should have no border.
- It would be nice if the cancel-icon (the X) would be of a dark-grey color.
- It would be very helpful if the functionality of clicking on the cancel (X) button would also be applied when hitting the esc key in the search-input-field (`(keyup.esc)="..."`)

Some additional possible improvements and comments
- It would be nice if the search input field would be focused when clicking on the search icon. This might be tricky to implement, but this [link](https://stackoverflow.com/questions/51566012/focus-an-element-after-it-appears-via-ngif) might help.
- Use the „==„ operator only, if you really mean to, else use the „===„ operator
- I think the pipe is general enough so that the „history“ parameter could be renamed to „map“ or something the like

**Comment by earthshakira** [comment]
Okay, looking into it.

**Comment by earthshakira** [comment]
@nilshansen94  I've made the changes,
 - have added a border:none for the empty class in scss
 - had to add focus() with a timeout as shown in [this article.](https://davidmcintosh.medium.com/auto-focusing-an-angular-input-the-easy-way-part-2-directives-ac9dc9a7ec73)
 I can replace it with the original reference you provided if this is a poor way of doing it, please guide me. Thanks.

**Comment by nilshansen94** [comment]
Thank you for the changes, @earthshakira!
The solution with the timeout and `hidden` works well.
One last thing: the "History" title in the card header is not aligned properly anymore, because the button is higher that the text. This can be fixed by removing the float-right class on the button-wrapper and adding the following CSS to the header list-group-item (preferrably by assigning a CSS id to the list-group-item header):
`display: flex;
justify-content: space-between;
align-itmes: center;`
(see this [link](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) for more information about flex)

**Comment by earthshakira** [comment]
@nilshansen94 Thanks for the feedback

Are there any drawbacks for using this approach over the id one for centring the `History` heading?
```SCSS
#history {
    .header {
       <the flex code here>
   }
}
```

**Comment by nilshansen94** [comment]
Hi @earthshakira, thank you for your changes. Your suggestion is a bit cleaner, because it doesn't introduce an extra id. But the committed solution is good as well, so we'll merge now.

**Review by nilshansen94 — APPROVED** [review]
Thanks @earthshakira for your changes!

**Comment by earthshakira** [comment]
@nilshansen94 Thanks for the quick responses and merge, contributing was pretty fun.

**Pull request merged**
