### PR TITLE
Dynamic Database Exploration

### PR DESCRIPTION
**Pull request by datomo**
This pull request extends the frontend by adding dynamic querying. This feature is enabled in the Graphical Querying interface. 

**Major Changes:**
- refinement options component added
- extended graphical querying sql generation

### CODE REVIEW

**Comment by nilshansen94** [comment]
I changed the layout of the btn-groups from horizontal to vertical to avoid layout problems.
There is still a todo in the crud service (allStatistics method). You might want to remove the comments in this method.
Else we are good to go.

**Comment by datomo** [comment]
Thanks @nilshansen94 for the review.
The vertical alignment seems kinda unsetteling for the user
grafik

So I would suggest to use flex-wrap on the buttons, so they just wrap when they don't have enough space and stay horizontal normaly, what do you think?
grafik

**Comment by nilshansen94** [comment]
@datomo what do you think about using select-menus? That would solve quite a few problems. For me, the vertical alignment with wrapping doesn't look very pretty.

**Comment by vogti** [comment]
What do you think about keeping the vertical buttons for sorting but use a select menu for the aggregation functions?

**Comment by isabelge** [comment]
grafik
I tried different things and I think @vogti idea looks good.

**Pull request merged**
